VENTANA_ANCHO = 766
VENTANA_ALTO = 960
VENTANA_DIMENSIONES = (VENTANA_ANCHO, VENTANA_ALTO)
VENTANA_TITULO = "Preguntados"
VENTANA_ICONO = "./assets/game_icon.png"

FUENTE = "./assets/Monocraft.otf"

COLOR_NEGRO = "#131313"
COLOR_BLANCO = "#f1f1f1"
COLOR_GRIS = "#afafaf"

MENU_FONDO = "./assets/fondo.png"

BOTON_FUENTE_TAMAÑO = 40
BOTON_ALTO = 120
BOTON_ANCHO = 500
BOTON_BORDE_RADIO = 30
